### ISSUE TITLE
IdChannel enums: Odd Behaviour for some channels

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#101]
For the PulseCandidateFinder, I am now setting some initial estimates at the parameter values we want like so:

``` c++
if (theChannel == IDs::Fast) {

    int rise = 0; // the parameter for this algorithm
    switch(theChannel.Detector()) {
    case IDs::kMuSc:
      rise = 300;
      break;

    case IDs::kMuScA:
      std::cout << "Here\n";
      rise = 100;
      break;

    case IDs::kNDet:
      rise = 100;
      break;

    ...
    default:
      std::cout << "Error: PulseCandidateFinder currently does not have a rise parameter for " << detname << std::endl;
      break;
}

```

However, in my output I see the error for channels muSc, muScA, SiL1-1-F, SiR1-1-F, SiL1-4-F, SiR1-2-F, SiR1-3-F and SiR1-4-F even though the `IDs::kXXX` are all handled in the switch (I also never see the "Here" print):

```
-----I'm debugging TemplateCreator::BeforeFirstEntry() 
Will analyse all 30 channels
Completed 0 events out of 1
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
muSc(CaBU): Pulse #6 has 7 pulse candidates <-- I guess it is using the value of 0 here
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
```

Any ideas what it could be?

**Comment by AndrewEdmonds11** [comment]
It might also be worth noting that this is how I get the IDs::Channel enum:

``` c++
std::string detname = TSetupData::Instance()->GetDetectorName(fPulseIsland->GetBankName());
IDs::channel theChannel = detname;
```

**Comment by benkrikler** [comment]
How do you initialise the IDs? My guess is that the strings naming a channel weren't as consistent as I'd hoped or I used the wrong versions. I can increase the possible options so that it's case independent (maybe why muScA didn't work) and so hyphens are treated equally to underscores (may be the problem with the SiL1-[1-4]-F channels).

Could you print the string version of the id to check? 

I've been pulled back into comet work now but as soon as I can I'll fix up these classes with all the changes they need.

Sent from my mobile
AndrewEdmonds11 notifications@github.com wrote:For the PulseCandidateFinder, I am now setting some initial estimates at the parameter values we want like so:

if (theChannel == IDs::Fast) {

```
int rise = 0; // the parameter for this algorithm
switch(theChannel.Detector()) {
case IDs::kMuSc:
  rise = 300;
  break;

case IDs::kMuScA:
  std::cout << "Here\n";
  rise = 100;
  break;

case IDs::kNDet:
  rise = 100;
  break;

...
default:
  std::cout << "Error: PulseCandidateFinder currently does not have a rise parameter for " << detname << std::endl;
  break;
```

}

However, in my output I see the error for channels muSc, muScA, SiL1-1-F, SiR1-1-F, SiL1-4-F, SiR1-2-F, SiR1-3-F and SiR1-4-F even though the IDs::kXXX are all handled in the switch (I also never see the "Here" print):

-----I'm debugging TemplateCreator::BeforeFirstEntry() 
Will analyse all 30 channels
Completed 0 events out of 1
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
muSc(CaBU): Pulse #6 has 7 pulse candidates <-- I guess it is using the value of 0 here
Error: PulseCandidateFinder currently does not have a rise parameter for muSc
Any ideas what it could be?

**Comment by AndrewEdmonds11** [comment]
So, I snooped around IdChannel.cpp and found that the detector strings are wrong: MuSc should be muSc and SiR1_1 should be SiR1-1 etc. After making the changes it looks like this:

```
std::string IDs::channel::GetDetectorString(Detector_t det){
        std::string output;
        switch(det){
            case kErrorDetector : output="Unknown"; break ;
            case kAnyDetector : output="*"        ; break ;
            case kGe          : output="Ge"       ; break ;
            case kLiquidSc    : output="LiquidSc" ; break ;
            case kNDet        : output="NDet"     ; break ;
            case kNDet2       : output="NDet2"    ; break ;
            case kScGe        : output="ScGe"     ; break ;
            case kScL         : output="ScL"      ; break ;
            case kScR         : output="ScR"      ; break ;
            case kScVe        : output="ScVe"     ; break ;
            case kSiL1_1      : output="SiL1-1"   ; break ;
            case kSiL1_2      : output="SiL1-2"   ; break ;
            case kSiL1_3      : output="SiL1-3"   ; break ;
            case kSiL1_4      : output="SiL1-4"   ; break ;
            case kSiL2        : output="SiL2"     ; break ;
            case kSiR1_1      : output="SiR1-1"   ; break ;
            case kSiR1_2      : output="SiR1-2"   ; break ;
            case kSiR1_3      : output="SiR1-3"   ; break ;
            case kSiR1_4      : output="SiR1-4"   ; break ;
            case kSiR1_sum    : output="SiR1-sum" ; break ;
            case kSiR2        : output="SiR2"     ; break ;
            case kMuSc        : output="muSc"     ; break ;
            case kMuScA       : output="muScA"    ; break ;
        }
     return output;
}

IDs::Detector_t IDs::channel::GetDetectorEnum(const std::string& det){
     const char* names[IDs::num_detector_enums]={
             "*", "Ge", "LiquidSc", "NDet", "NDet2", "ScGe", "ScL", "ScR",
                "ScVe", "SiL1-1", "SiL1-2", "SiL1-3", "SiL1-4", "SiL2",
                "SiR1-1", "SiR1-2", "SiR1-3", "SiR1-4", "SiR1-sum", "SiR2",
                "muSc", "muScA" };
     for (int i=0;i<IDs::num_detector_enums;i++){
        if(det==names[i]) return (Detector_t)i;
     }
     return kErrorDetector;
}

```

I've changed them on my branch but I'll leave this issue open since Ben might want to out in a better fix.

**Comment by AndrewEdmonds11** [comment]
Looks like we replied at the same time. Yes, it's the case sensitivity and "-" vs "_". 

I knew you'd think of a better way to fix this than me :)

**Comment by litchfld** [comment]
Long term fix is to replace the TSetupData::GetDetectorName() to get enums from the bank string, and convert them to strings as Channel ID. of course we acnt do that becasue TSetupData can't depend on the Channel ID... so we should probably wait for a replacement for TSetupData. There may be a funky callback type fix but probably not worth implementing.

**Comment by thnam** [comment]
Then what should we do with this issue?
When I tried to get TAP from muSc, rootana always complained:

```
List of TPIs for 'muSc-*' was empty
```

For now, I'm using @AndrewEdmonds11 's fix and this:

```
@@ -71,7 +71,7 @@ IDs::channel& IDs::channel::operator=(const std::string& rhs){
 std::string IDs::channel::GetSlowFastString(SlowFast_t sf){
  std::string output;
  switch(sf){
-   case kAnySlowFast   : output+="-*" ; break ;
+   case kAnySlowFast   : output+="" ; break ;
    case kSlow          : output+="-S" ; break ;
```

**Comment by benkrikler** [comment]
This should be fine now, so I'm closing this issue.  I've added extra unit tests to check but feel free to re-open this if we get other odd behaviour...
