### ISSUE TITLE
Do we use exceptions?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#108]
The Bank Iterators that represent the result of a wildcard query to the EventNavigator should not be able to modify their query once they have started iterating. One way to ensure this is to make them throw exceptions if such an operation is attempted.  This can be caught or left alone to halt the program.

However our code mostly does not use exceptions, and one meta-rule for using them is you should be very wary about it if the majority of your developers don't use them.  So how do people feel about exceptions?

**Comment by AndrewEdmonds11** [comment]
I've never used them but know I really should. If this means I have to get my act together then that would be good thing.

**Comment by benkrikler** [comment]
I think I was a bit unaware of that rule, because I've put at least one exception in modules parser stuff.  I think I handle it myself by all the calling methods so it would only be if the function gets used elsewhere that it would cause a problem which I'm not expecting to occur.

Personally I think this is enough publicity that you'd be doing it that way, so I say go for it...

**Comment by litchfld** [comment]
Well actually I guess the rule is actually "If you don't just use them as a descriptive way to terminate() the program you should be wary" and I was basically going to do that.  So perhaps it isn't so important. 

I'll leave this open a little while longer and see if anyone objects.

**Comment by thnam** [comment]
I also think that we should use it. That would (hopefully) be a good chance to learn a proper exception handling ...

**Comment by litchfld** [comment]
``` C++
#include <exception>
class ECloseTheThread : public std::exception {
what() { return "This is a terrible example, and I will goto hell for it";}
};

throw  ECloseTheThread();
```
