### ISSUE TITLE
SQLite Code

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#119]
SQLite mentioned in issue #104, and I have a couple of (possibly naive) questions:
- Are we just talking about the SQLite stuff that's in ROOT?
- Would we have one SQLite database file for every use (pulse candidate finder, calibrations) or one for each?

**Comment by litchfld** [comment]
> Are we just talking about the SQLite stuff that's in ROOT?

Yes, the ROOT interface is fine. (There are others, and they can all be used with the same DB files - that's the point of using a standard protocol.)  But we need to recompile ROOT with it pointed to the SQLite installation, the Plugin is not available otherwise.

> Would we have one SQLite database file for every use (pulse candidate finder, calibrations) or one for each?

I am not sure. But it doesn't matter very much, so we can try it out and see. It is probably worth breaking them up a bit if we can, then individual components can be swapped out.  OTOH if the SQLite DB file is human-readable it is easy enough to edit them in place and git can provide the history.

**Comment by AndrewEdmonds11** [comment]
Ok, I'll check how to compile ROOT with SQLite and try using it for storing the pedestal and noise for the PulseCandidateFinder

**Comment by jrquirk** [comment]
We can also use the SQLite3 code instead of the ROOT plugin. From the documentation it seems either will work.

**Comment by litchfld** [comment]
I think the ROOT plugin is wrapping sqlite3 anyway.  So we'll need grab a SQLite distribution with source code in our install scripts. 

Using ROOT plugins in our main code is probably better since it minimises change if we subsequently switch to a full MySQL back-end.  But the SQLite3 standalone may be a handy tool for management.

**Comment by AndrewEdmonds11** [comment]
I have now added an install script for sqlite on my latest feature branch (4a07415674f224a8c3c90b7fbe83e3cd18ec707b) and also modified thisdaq.sh to find it.

I haven't yet tested whether I can use it within rootana

**Comment by AndrewEdmonds11** [comment]
As of 365fd01b353d254988d387291ca5c28a5263590c, I can now write pedestal and noise values to an SQLite database.

I will now try and read in but I have a question about the format of the table.

Currently, I just have Channel, Bank, Pedestal and Noise but do we also want run number? And, if so, how can I get the run number from within a module?

**Comment by benkrikler** [comment]
> how can I get the run number from within a module?

This came up before I think.  I'll add a method in somewhere and commit it shortly.

**Comment by AndrewEdmonds11** [comment]
This is now finished with the above commit. The only outstanding thing is to add run numbers to the sqlite database.

I'm going to write up a load of documentation for all the stuff I've done so far with the PulseCandidateFinder since I've neglected it.
