### ISSUE TITLE
Current Problems with Template Fitter

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#129]
This is mostly for @jrquirk but if anyone else has any ideas about what's going on then do get involved.

Currently, nothing seems to be getting fitted with pedestals, amplitudes and times O(10^-312), which looks like an uninitialised variable problem, and chi^2 are O(10^4).

This is on the develop branch (you will need to uncomment parts of TemplateCreator.cpp and also set `print_dbg = true` in HistogramFitFCN.cpp to see what I'm talking about). 

Also, I am working on the branch `feature/finalise_template_creator` which has become a bit of a mess with a lot of extra debug statements and some other things I've tried which now give me a slightly different problem (see later).

I have a few questions for John and will try to make reference to the correct branch and file that I'm talking about:
- in your calculation for chi^2 (HistogramFitFCN.cpp, develop):  
  - only H1 is used and not H2. Is this correct?  
    - talking to Phill, this sounded wrong so I changed it on the feature branch but it didn't seem to make things any better  
  - you calculate f as `f = A*f + P` but isn't the pedestal already included from f since we get it from the digitised waveform? Or should we be creating our histograms with the pedestal subtracted?  
  - when we get the bin content in the `i-T_int` bin, we risk asking ROOT for the underflow bin. Could this be a problem? There shouldn't be anything in it but I'm not sure if having it as 0 would be a problem as well
- general questions:  
  - do we not need to make initial estimates at the parameters? Currently, they are left uninitialised  
    - I tried this on the feature branch in TemplateFitter.cpp (not much effect, just returned the estimates)  
  - should a TemplateFitter be created for each channel like the PulseCandidateFinder?

Some of these things I may not have ported over from your code correctly so let me know if it should be in there.

Finally, through some combination of messing about, I do seem to find minima but the values don't seem to get returned correctly. This is going to be in the commit that I'll refer to in a second. The output I get (with some notes added) is this:

```
Will analyse all 30 channels
Completed 0 events out of 1
Parameter Value for MuSc PulseCandidateFinder is 300
Parameter Value for Ge-S PulseCandidateFinder is 500
TFitterMinuit - Minimize with max iterations = 0 edmval = 0.1 errorDef = 1
Fit:    Chi2 386469     P 6.8498e-311(6.8498e-311)      A 6.84768e-311(6.84768e-311)    T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 386458     P 0.0303548(0.0303548)  A 6.84768e-311(6.84768e-311)    T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 386479     P -0.0303548(-0.0303548)        A 6.84768e-311(6.84768e-311)    T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 386365     P 0.303548(0.303548)    A 6.84768e-311(6.84768e-311)    T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 386573     P -0.303548(-0.303548)  A 6.84768e-311(6.84768e-311)    T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 370737     P 6.8498e-311(6.8498e-311)      A 0.0303548(0.0303548)  T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 402552     P 6.8498e-311(6.8498e-311)      A -0.0303548(-0.0303548)        T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 384880     P 6.8498e-311(6.8498e-311)      A 0.00303548(0.00303548)        T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 388061     P 6.8498e-311(6.8498e-311)      A -0.00303548(-0.00303548)      T 0 6.83919e-311(6.83919e-311) 0.02345
Fit:    Chi2 386469     P 6.8498e-311(6.8498e-311)      A 6.84768e-311(6.84768e-311)    T 0 0.303548(0.303548) 0.02345
Fit:    Chi2 386469     P 6.8498e-311(6.8498e-311)      A 6.84768e-311(6.84768e-311)    T 0 -0.303548(-0.303548) 0.02345
Fit:    Chi2 388442     P 6.8498e-311(6.8498e-311)      A 6.84768e-311(6.84768e-311)    T 3 0.0354831(3.03548) 0.02345

...

Fit:    Chi2 10489.4    P -1610.25(-1610.25)    A 2.49722(2.49722)      T 3 0.999051(3.99905) 0.02345
Fit:    Chi2 10489.4    P -1610.25(-1610.25)    A 2.49699(2.49699)      T 3 0.999051(3.99905) 0.02345
Fit:    Chi2 10489.1    P -1610.25(-1610.25)    A 2.4971(2.4971)        T 3 0.999875(3.99987) 0.02345
Fit:    Chi2 10489.8    P -1610.25(-1610.25)    A 2.4971(2.4971)        T 3 0.998227(3.99823) 0.02345
Minimum Found <--- Yay!
FVAL  = 10489.4377832582904
Edm   = 3.33994217890917414e-06
Nfcn  = 431
Pedestal          = -1610.25      +/-  12.1842    <---
Amplitude         = 2.4971        +/-  0.00880651 <--- Aren't O(10^-312) any more
Time      = 3.99905       +/-  7.93165e-06         <---
Fit:    Chi2 386469     P 6.8498e-311(6.8498e-311)      A 6.84768e-311(6.84768e-311)    T 0 6.83919e-311(6.83919e-311) 0.02345 <--- !! This is at the end of HistogramFitFCN::operator()
Ge-S(CaUH): Pulse #8: Fitted Parameters: Ped = 6.8498e-311, Amp = 6.84768e-311, Time = 6.83919e-311, Chi2 = 386469 <--- These are the values that are seen in TemplateCreator
```

I guess that's a lot to digest but I'll keep working on it today and I'll hopefully make a bit more progress.

**Comment by AndrewEdmonds11** [comment]
Solved the last problem with parameter values not being returned correctly. I needed to get the fitted values after we call Minimize():

``` c++
  // Minimize and notify if there was a problem
  int status = fMinuitFitter->Minimize();
  if (status != 0)
    std::cout << "ERROR: Problem with fit (" << status << ")!" << std::endl;

  // Get the fitted values
  fPedestal = fMinuitFitter->GetParameter(0);
  fAmplitude = fMinuitFitter->GetParameter(1);
  fTime = fMinuitFitter->GetParameter(2);

  // Store the Chi2, and then we can delete the pulse
  std::vector<double> params;
  params.push_back(fPedestal);
  params.push_back(fAmplitude);
  params.push_back(fTime);
  fChi2 = (*fcn)(params);
```

Although, I don't know how or where HistogramFitFCN::operator() gets called a second time after minimisation....

**Comment by AndrewEdmonds11** [comment]
> Although, I don't know how or where HistogramFitFCN::operator() gets called a second time after minimisation....

It's from this line:

```
fChi2 = (*fcn)(params)
```

which just recalculates the chi^2 for us. (I should really think before posting every problem I have)

**Comment by litchfld** [comment]
We spoke directly but here are some comments for posterity:

> -   do we not need to make initial estimates at the parameters? Currently, they are left uninitialised

Absolutely. Minuit can go to a very dark place if it doesn't start out somewhere near the minimum.  They don't have to be all that good but sane estimates improve things a lot, how about:
- Content of first bin for pedestal
- Max/min bin content (- pedestal) for amplitude
- Difference of two histogram max bins (in same units as Time; is it just bins?) for the alignment.

> -  Should a TemplateFitter be created for each channel like the PulseCandidateFinder?

Certainly they should all be different templates, but if you are talking about instances it's less obvious. It might be preferable, since you are less likely to accidentally carry over some data. (OTOH if you didn't that makes you more careful)

**Comment by AndrewEdmonds11** [comment]
> you calculate f as f = A*f + P but isn't the pedestal already included from f since we get it from the digitised waveform? Or should we be creating our histograms with the pedestal subtracted?

So it wasn't until I was getting negative pedestals that I realised that this is more of a pedestal offset and so my questions are moot.

I have renamed pedestal, amplitude and time in the TemplateFitter to be pedestal offset, amplitude scale factor and time offset since I think this is what these parameters actually are.

**Comment by AndrewEdmonds11** [comment]
So Phill and I have managed to get at least one pulse in Ge-S to align with the template. This is in the above commit and a picture is here:

![run2808_allaligned](https://cloud.githubusercontent.com/assets/1848575/3398643/ba3ff6ea-fd32-11e3-9721-7fb3d70dca33.gif)

While we were doing it, there were a couple of things that would make more logical sense to me if they were swapped. Specifically,
- currently, we get the scale factor and pedestal offset for the _template_ relative to the _pulse_, I propose to swap these around
- it might also be best to start with a pedestal subtracted template

I'll make these changes today and also tidy up the code a bit before continuing on with the TemplateCreator.

**Comment by jrquirk** [comment]
> do we not need to make initial estimates at the parameters? Currently, they are left uninitialised

This was originally done [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/legacy/MakeTemplate.cpp#L72-L75). Some of it is what @litchfld suggested, both should work and are quick to calculate.

> isn't the pedestal already included from f since we get it from the digitised waveform?

The pedestal is still one of the three fit parameters, the one we get from the waveform could be an initial estimate.

> only H1 is used and not H2. Is this correct?

No, as @litchfld said, you need to use both. If both weren't initially used, it was a tpyo. To be clear what's going on is
1. You linearly interpolate between two bins to find what the sub-bin amplitude is according to the, uh, time offset
2. You scale according to the amplitude and add according to the pedestal
3. You take the difference of this value with the template squared, divided by the error on the template squared.

So if that's not happening, it's a logical error in the code.

> when we get the bin content in the `i-T_int` bin, we risk asking ROOT for the underflow bin. Could this be a problem? There shouldn't be anything in it but I'm not sure if having it as 0 would be a problem as well

This should be taken care of by deciding the bounds [earlier](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/TAP_generators/utils/HistogramFitFCN.cpp#L33-L35). There's issues of shifting by too much having too few bins included in the fit, so there might need to be some normalization for this, but I hadn't solved that issue yet.

> - currently, we get the scale factor and pedestal offset for the template relative to the pulse, I propose to swap these around
>   *it might also be best to start with a pedestal subtracted template

I don't understand the first. Is the template shifted and scaled or the pulse shifted and scaled? And the second, you mean have a template with a pedestal of zero?

**Comment by jrquirk** [comment]
Also you can test the different fitters by just making dummy pulses from the same function. Digitize something like A*(exp(-t/tau1)-exp(-t/tau2)) and call that the template, then add small pedestal and timing offset, as well as scale, digitize, and see if you get the correct fit values back.

**Comment by AndrewEdmonds11** [comment]
> I don't understand the first. Is the template shifted and scaled or the pulse shifted and scaled?

Originally, it was the template that was getting shifted and scaled to match the given pulse. This meant I had to reverse all the operations when I want to correct a pulse (i.e. `corrected_pulse = (uncorrected_pulse - pedestalOffset) / amplitudeScaleFactor`. I want to swap these around so that HistogramFitFCN transforms the pulse to the template.

> And the second, you mean have a template with a pedestal of zero?

Yes, although I'm not as ideologically set on this as on the other change :)

Good idea about the testing of the fitters. I'll look into it

**Comment by AndrewEdmonds11** [comment]
Also, I meant to write this straight after the post where I show a good Ge-S pulse correction.

Here's a (very) poor Ge-F pulse correction:
![run2808_notaligned_ge-f](https://cloud.githubusercontent.com/assets/1848575/3399048/89eea46e-fd37-11e3-94d2-855d04369633.gif)

I'm guessing this is a polarity problem somewhere...

**Comment by jrquirk** [comment]
> This meant I had to reverse all the operations when I want to correct a pulse

But later on, when you're doing fitting, the values you want return are the actual amplitude, pedestal, and time. So if you have a template that's been normalized so that the amplitude is 1 and the pedestal is zero, and then the fit values scale and shift this pulse, the values you wind up getting are what you put into the TAP. This mean you have to reverse the calculation when building the template, yes, but in the end it will be nicer when fitting it to a pulse you don't plan on adding.

The timing offset I don't think has a natural value like the pedestal (0) and amplitude (1).

**Comment by AndrewEdmonds11** [comment]
Ah, good point, I hadn't thought that far ahead. I'll leave it as it is then.

**Comment by AndrewEdmonds11** [comment]
I've managed to get the Ge-F pulses to align now. It was because I wasn't taking the polarity of the pulse into account when making the time estimate.

![run2808_aligned_ge-f](https://cloud.githubusercontent.com/assets/1848575/3400844/287a4406-fd49-11e3-9f0d-efd4b231d7fa.gif)

**Comment by litchfld** [comment]
> This should be taken care of by deciding the bounds earlier. There's issues of shifting by too much having too few bins included in the fit, so there might need to be some normalization for this, but I hadn't solved that issue yet.

Ah, because if you drive the histograms so far out of alignment the nDOF in the fits drops and improves the chi^2. Yes. Hmm. Probably the correct way to deal with that is to calculate the chi^2 probablity for the appropriate nDOF (nBins-3 I think?) and maximise that. e.g. instead of returning the 'chi^2' test statistic (let's call it `X2`), return `TMath::Log(TMath::Prob(X2,nBins-3))`  

Probably returning `X2 - nBins` would also work in all but the most frunky of corner cases.

**Comment by AndrewEdmonds11** [comment]
Talking through things with Phill a bit, there are a couple of things that I need to add/correct:
- get the bin errors for the pulse and template histograms correct
  - currently the way we create the pulse histogram is that ROOT automatically sets the bin errors to be `sqrt(contents)` where what we want is the noise on the pedestal (from the SQLite database created by PlotPedestalAndNoise)
  - at the moment, there's a function in TemplateFitter that gets the noise from the SQLite database but I guess this needs to be moved to TSetupData (or whatever the new class is called). I'll open an issue for this.
  - for the error on the template, we need to update the errors as we add pulses
  - it would also be nice to have the bin errors correct in the histograms produced by the ExportPulses module so that we can draw them
- we should also record the number of degrees of freedom that we are fitting to
  - this is `no. of bins we are fitting to (i.e. within bounds[0] and bounds[1]) - no. of fit parameters (i.e. 3)` so that we can calculate the probability should we need to

Apologies if that was a bit of a rambling post

**Comment by jrquirk** [comment]
A note on the errors, you can see how a running standard deviation was kept track of [here](https://github.com/alcap-org/AlcapDAQ/blob/feature/finalise_template_creator/analyzer/rootana/src/TAP_generators/legacy/PulseTemplate.cpp#L116-L127) in the old code. It's a standard way to keep track of averages/std.dev. If there's noise in the pedestal, it might already be taken into account there since it's a random error. But I'm not sure.

**EDIT**: http://en.wikipedia.org/wiki/Standard_deviation#Rapid_calculation_methods

**Comment by litchfld** [comment]
> If there's noise in the pedestal, it might already be taken into account there since it's a random error.

I think that's right.  Once the template stabilises the difference between it and a new pulse should have two components (per bin): The random sample error of the pulse and the template uncertainty (which is a measure of how much pulses deviate from each other in ideal conditions).  If the same pulse could be measured many times it should converge on some true shape, but not necessarily the template.  But the point of the template method is this true shape of a single pluse, averaged over many pulses, averages to the template shape. 

So we have five quantities (_i_ runs over bins): 
![img](http://www.sciweavers.org/tex2img.php?eq=%5Ctextrm%7BPulse%20value%3A%7D%26%26%20p_i%5C%5C%20%0A%5Ctextrm%7BSingle-pulse%20expectation%20value%3A%7D%26%26%5Coverline%7Bp%7D_i%5C%5C%0A%5Ctextrm%7BSingle-pulse%20random%20uncertainty%3A%7D%26%26%20%5Csigma_%7B%5Cmathrm%7B1%3B%7Di%7D%20%5Csimeq%20%5Csigma_%7B%5Cmathrm%7Bped%7D%7D%5C%5C%0A%5Ctextrm%7BTemplate%20value%3A%7D%26%26%20T_i%5C%5C%0A%5Ctextrm%7BTemplate%20uncertainty%3A%7D%26%26%20%5Csigma_%7B%5Cmathrm%7BT%3B%7Di%7D%20%3D%20%5Csqrt%7BE%5Cleft%5B%28T_i%20-%20%5Coverline%7Bp%7D_i%29%5E2%29%5Cright%5D%7D%0A&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)

Then we have: ![img](http://www.sciweavers.org/tex2img.php?eq=p_i%20%5Csim%20G%28%5Coverline%7Bp%7D_i%20%2C%20%5Csigma_%5Cmathrm%7Bped%7D%29%5Ctextrm%7B%3B%5Cquad%20i.e.%20%7D%20E%5Cleft%5Bp_i%5Cright%5D%20%3D%20%5Coverline%7Bp%7D_i%20%5Ctextrm%7B%2C%5Cquad%7D%20E%5Cleft%5B%28p_i-%20%5Coverline%7Bp%7D_i%29%5E2%5Cright%5D%20%3D%20%5Csigma_%5Cmathrm%7Bped%7D%0A&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)

and by definition: ![img](http://www.sciweavers.org/tex2img.php?eq=%5Csigma_%5Cmathrm%7BT%7D%20%3D%20%20E%5Cleft%5B%28T-%20%5Coverline%7Bp%7D_i%29%5E2%5Cright%5D%0A&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)

So once the template has stabilised, if we track the RMS of the difference ![img](http://www.sciweavers.org/tex2img.php?eq=T-p_i%0A&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0), either directly as John suggests or indirectly from a histogram, we should get:

![img](http://www.sciweavers.org/tex2img.php?eq=E%5Cleft%5B%28T_i-p_i%29%5E2%5Cright%5D%20%26%3D%26%20E%5Cleft%5B%28T_i-%5Coverline%7Bp%7D_i%2B%5Coverline%7Bp%7D_i%20-%20p_i%29%5E2%5Cright%5D%5C%5C%0A%26%3D%26%20E%5Cleft%5B%28T_i-%5Coverline%7Bp%7D_i%29%5E2%5Cright%5D%20%2B%20E%5Cleft%5B%28%5Coverline%7Bp%7D_i-p_i%29%5E2%5Cright%5D%20-%20E%5Cleft%5B%28T_i-%5Coverline%7Bp%7D_i%29%28%5Coverline%7Bp%7D_i-p_i%29%5Cright%5D%5C%5C%0A%26%3D%26%20%5Csigma_%7B%5Cmathrm%7BT%3B%7Di%7D%5E2%20%2B%20%5Csigma_%5Cmathrm%7Bped%7D%5E2%20%2B%20%5Cdelta&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)

Where the last term is a cross-correlation that we assume tends to zero, because it is the product of two quantities that should be independent.

So the computed RMS should, in the long run, tend towards the template error added in quadrature with the single pulse error.  This should be the right error for computing the chi2 of a pulse compared to the template.  

The caveat is that this strictly only applies after an infinite number of pulses have been added to the template. for a finite term there is another error for "how far my template is from the ideal template"  When combining the first+second pulse for example, the template has roughly the same errors as the pulse, and this ignored error is large.  A possible fix is to seed the template and error estimates with a number of pulses (5~10?) during which time the error assumed is just sqrt(2) \* the single pulse error.  Or one could just ignore this, assuming the initial burn-in will contribute very little in the long run.

**Comment by AndrewEdmonds11** [comment]
Ok, I haven't been updating this much but this is now pretty much done. See my presentation in [elog:148](https://muon.npl.washington.edu/elog/mu2e/Analysis-R13/148) for the updates up until yesterday.

Updates for today:
- in yesterday's meeting it was mentioned that the transformation should be `amp_scale_factor*(sample_value - tempalte_pedestal) + ped_offset` with ped_offset outside of the bracket
  - everything looked nicer after this
- also, it was mentioned that we should only interpolate the first pulse that gets added to the template and none of the later ones
  - this initially ended up with "boxy" templates again, which is because there is a bonus to matching all sub-bins together
  - so I changed HistogramFitFCN to only calculate chi^2 from the central sub-bin of each bin

Here are some plots of the new templates (run 2808, 1 event):
![musc](https://cloud.githubusercontent.com/assets/1848575/3611687/98d990e8-0d9e-11e4-9e25-fb89d0a290fe.png)
![ge-s](https://cloud.githubusercontent.com/assets/1848575/3611688/9c2ef9ae-0d9e-11e4-88cc-22fe9cbd4c49.png)
![musca](https://cloud.githubusercontent.com/assets/1848575/3611689/9f468e9a-0d9e-11e4-89a7-1b78e1598f97.png)
![ge-f](https://cloud.githubusercontent.com/assets/1848575/3611690/a1e54b96-0d9e-11e4-9db0-311bd2963e0e.png)
![ndet](https://cloud.githubusercontent.com/assets/1848575/3611691/a4a036c0-0d9e-11e4-803f-fd1ab925f086.png)
![sil2-s](https://cloud.githubusercontent.com/assets/1848575/3611694/a6c99fae-0d9e-11e4-864d-582b3fa481b9.png)
![scl](https://cloud.githubusercontent.com/assets/1848575/3611695/a9f3c6f0-0d9e-11e4-96a8-7c1355993b13.png)
![scr](https://cloud.githubusercontent.com/assets/1848575/3611696/abfa480c-0d9e-11e4-9474-673d97b2df1a.png)
![scge](https://cloud.githubusercontent.com/assets/1848575/3611697/aec799fe-0d9e-11e4-8610-505538d5bf05.png)
![scve](https://cloud.githubusercontent.com/assets/1848575/3611701/b0d6e2a4-0d9e-11e4-871d-22ac3f5d0ecf.png)

I'm going to close this issue and open a new one for the last few things that need doing for TemplateCreator since there are no more problems (yet)
