### ISSUE TITLE
Alcapana Run 3 (Attempt 3) Picture Books...

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#145]
...are now on the [dropbox](https://www.dropbox.com/home/AlCap/R2013/PictureBooks/prod-run-3-attempt-3)

@thnam, could you check that the muSc TDiffs are now aligned and I'll do the amplitude plots?

**Comment by AndrewEdmonds11** [comment]
PNGs have now been sent to Ben and John. If anyone else wants them then let me know

**Comment by AndrewEdmonds11** [comment]
Ok, so there are a few channels that didn't seem to align. I will look through the dump logs to see what's happened but here are the wrong ones so far:

Al100:
![hdq_islandamplitude_sil1-2-f_nd81_ped_sub_trendplot](https://cloud.githubusercontent.com/assets/1848575/3493835/9943513e-05bc-11e4-918b-f584abe54ee3.png)
![hdq_islandamplitude_sil1-3-s_nc82_ped_sub_trendplot](https://cloud.githubusercontent.com/assets/1848575/3493840/a57878d0-05bc-11e4-86dd-49a306a67ff2.png)
![hdq_islandamplitude_sir2-f_nb81_ped_sub_trendplot](https://cloud.githubusercontent.com/assets/1848575/3493842/adaccf1a-05bc-11e4-8512-3aeeebf1e81c.png)

Al50(a) without NDet2:
![hdq_islandamplitude_sil1-3-s_nc82_ped_sub_trendplot](https://cloud.githubusercontent.com/assets/1848575/3493850/c2ba5724-05bc-11e4-8280-b6af1d3a5a7d.png)

**Comment by AndrewEdmonds11** [comment]
So I've looked into the large tranche of Al100 runs (2963 - 2992), specifically SiL1-2-F (element 11 in the WireMap) and we have the following:

| Run | Original ODB Pedestal Value | Correction ODB Pedestal Value | Dump ODB Value |
| --- | --- | --- | --- |
| 2963 | 1300 | 1455 | 1455 |
| 2964 | 1300 | 1455 | 1455 |
| 2965 | 1300 | 1455 | 1455 |

so this means that the ODB correction _is_ being loaded, which is good. However, when we look at the plot before the correction is made:

![hdq_islandamplitude_sil1-2-f_nd81_trendplot](https://cloud.githubusercontent.com/assets/1848575/3494192/a99d435a-05c1-11e4-82c3-74b843dcc7f9.png)

that 2964 needs a much larger correction than run 2963. @jrquirk, how does your ODB check get the value for the pedestal?

This may not matter too much since we can obtain pedestal values with rootana so (hopefully) we don't need to do another alcapana run

**Comment by jrquirk** [comment]
The pedestal is determined [here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/odb_check/src/PulseEstimate.cc#L12-L26) by
1. Projecting the first 10 x-bins of the shapes plot onto the y-axis.
2. Changing the projection range (originally 0 to 2^nbits-1) to ignore the 5 bins on the edges (5 to 2^nbits-6)
3. Find the ADC value of the highest bin

So the shapes histogram should show the problem. If not, it could also be in the amplitude calculation.

**Comment by jrquirk** [comment]
It's the trigger polarity. 2964 is "corrected" to have a trigger polarity of -1 even though it should be +1.

**Comment by AndrewEdmonds11** [comment]
So, why did that happen? Because it doesn't seem to wrong anywhere else it must be some weird edge case.

Here's the pulse shapes plot for it:

![run2964_pulseshapes_sil1-2-f](https://cloud.githubusercontent.com/assets/1848575/3498227/7bf23442-05f3-11e4-8ae8-6e5a4384da1c.png)

It's pretty obvious that this could screw up the algorithm in ODB check. John, can you think of a way to solve this? If not, then we can always "hard-code" these since they should be pretty obvious from the detector names

**Comment by jrquirk** [comment]
The algorithm for finding the polarity is:
1. Find the pedestal using the method above
2. Take the _entire_ y-projection.
3. Look for the first non-zero bin at ADC values higher than the pedestal and lower than the pedestal, ignoring the first 5 bins on each side

The idea behind this is that the largest pulse, negative or positive, decides what the polarity is. At first glance this seems like a fine method. The problem here is that the largest pulse for some positive channels was actually negative going.

> So, why did that happen?

To me it seems the algorithm failed here because the channels are crap. We can put a fix in, but I suggest we also consider ignoring these channels.

**Comment by AndrewEdmonds11** [comment]
> but I suggest we also consider ignoring these channels.

Ok, so how did we decide to do this? Is this using the run database at UW, where we add a flag for each channel to each run that says whether it's good for analysis not?

**Comment by benkrikler** [comment]
I've updated the webpage with the new plots:
http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_3/by_detector.shtml

I've looped through some of the detectors:
- I'm still seeing timestamp banding though perhaps not as pronounced
  ![hDQ_IslandTimestamp_SiL1-2-S_TrendPlot from Al50a_without_NDet2](http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_3/plots/data_quality_figs_Al50a_without-NDet2/byDetectors/hDQ_IslandTimestamp_SiL1-2-S_TrendPlot.png)
- Some of the TDiff plots don't seem to align the peak well around 0
  ![hDQ_MuSCTDiff_SiL1-2-S_TrendPlot from Al100](http://www.hep.ph.ic.ac.uk/~bek07/alcap/trend_plots/production_3/plots/data_quality_figs_Al100/byDetectors/hDQ_muScTDiff_SiL2-S_TrendPlot.png)

**Comment by litchfld** [comment]
> To me it seems the algorithm failed here because the channels are crap. We can put a fix in, but I suggest we also consider ignoring these channels.

Hhmmm... so, in this particular case we know the trigger threshold is too low for the noise.  I can come up with three general categories for what the noise is, based on 
- **source**    If it is coupled to a real signal (like a under-damped oscillator), or due to an independent source (e.g. flaky power supply) 
- **duration**   If it is independent from the source, is it constant, or coming in bursts?

The possibilities are:
1. Independent, bursty noise: This is not so bad, the channel may actually be fine for the majority of the time, event though the noise is much more common than the signal (these are not inconsistent if _signal length_ x _rate_ << 1)
2. Independent constant noise: This is worse, but if the pulses are larger than the noise you may still be able to cope, albeit with a increase in uncertainties.
3. Coupled noise:  Bad because all signals are a mess. You might be able to count pulses even then.
4. Coupled noise, with independent source of noise events: Disastrous, because you cant work out the shape or rate of the signal.

We know (because the rates are high) that there must be an independent noise source.  We can suspect that the noise is not constant because the waveforms after the trigger die off. That leaves cases **1** and **4**.  So it might be okay...

Unfortunately Andy says this waveform overlay is from an entire run, and we see no points outside 700~2200ADC. 

So it seems like there are no identifiable signals, and we are in case **4** . One could be optimistic and imagine that the spray between the the trigger peak and the next peak is evidence of real signals with an amplitude similar to the noise, but _if_ that were the case, it's still going to be very hard to extract the signals. So  i'm coming round to the idea we junk the channels... does that mean we also junk the runs?  And are the other noisy runs without wrong polarity also junk?

**Comment by jrquirk** [comment]
> So it seems like there are no identifiable signals

Additionally, the pulse height distribution hDQ_Amplitude_SiL1-2-F_Nd81 (last plot in third post) is evidence supporting this (the peppered signals above threshold) for all runs in the dataset, as even when we do have some signals we don't have many.

> does that mean we also junk the runs

Let's cling to hope the slow channels have something. And if not then the other segments so that we can just reduce the arm's solid angle instead of throwing out the run. When calculating rates that might make these silver runs, but other analysis they might still be gold.

> Ok, so how did we decide to do this?

I don't think we have. For now maybe a software threshold might offer the same effect unless someone wants to work on a an enabled-channel database. I can also put a fix in the [ODB check](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/odb_check/src/WireMap.cc#L74-L89) for this, disabling the channel in TSetupData for certain runs. At this point I don't think anyone does checks for channels being enabled/disabled.

**Comment by AndrewEdmonds11** [comment]
Just to summarise what we discussed in the meeting:
- the TDiffs issue was just Ben looking at the wrong plots (the time shifted ones look fine)
- for the dodgy channel, we will eventually have an SQLite database with a flag for each channel saying whether it's OK to analyse

I'll close this now and open a new issue for the task above
