### ISSUE TITLE
Filling of gAnalysedPulseMap?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#158]
I'm attempting to merge the event navigator branch with develop, but I am unable to (usefully) run the executable.  I get the following output:

```
Will analyse 2 of 28 channels
Processed        0 / 1000       (0%)
Error: New TAP source seems to have been created during processing of pulses.
Unable to find source for fast channel: SiR2-F#MaxBinAPGenerator#default
gAnalysedPulseMap contains:

```

where that last line is empty because gAnalysedPulseMap is empty.  To the best of my memory I haven't touched this code though, so I'm not sure where to look. how does gAnalysedPulseMap get filled and has that mechanism changed recently?

**Comment by benkrikler** [comment]
AFAICR, I changed it a little before the production run so that `MakeAnalysedPulses` filled `gAnalysedPulseMap` with a TPI list for each source that was to be run with in the `BeforeFirstEntry` method.  Then, it would check in `ProcessEntry` that a TPI list existed for the source it was looking at and if not it would spit out that error you've seen.  It was to try and protect against an error Andy uncovered (I'm afraid I can't remember the ticket number but it was one of the rootana ID class ones I think).

My guess is you need to update the BeforeFirstEntry method as it's no longer creating a TPI list for each source correctly.

**Comment by benkrikler** [comment]
I've been testing code on develop and don't see this problem now so I'm going to close this issue as I think its been finished, though feel free to reopen if I'm wrong.
