### ISSUE TITLE
AlcapExcept uses c++11's snprintf so doesn't compile on older gcc

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#161]
The problem line is:
https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/AlcapExcept.cpp#L86

The simple solution is probably to increase the c-string buffer's size and use good ol' sprintf.

**Comment by benkrikler** [comment]
Actually,  it seems the problem was because `<cstdio>` wasn't included, but the `snprintf` method was brought in during with the c++11 standard, so I'm not sure where it falls with our policy on c++11.  As long as it works for everyone I guess we can leave it in.

**Comment by AndrewEdmonds11** [comment]
It doesn't work for me :(

**Comment by AndrewEdmonds11** [comment]
Actually, it did compile once I actually added the fix you suggested...

**Comment by litchfld** [comment]
Ah good,  snprintf should be available with venerable old gcc 4.3 (admittedly as C99), so that weirded me out a bit.

In any case the buffer is pretty generous (15 characters plus '\0', to hold a line number in a text file) so switching to sprintf would have been fine in all ~~sane~~ use cases.

_EDIT_ Actually call it a all 'plausible' use cases (sane is optional), given that the range of a 32-bit `int`is noticeably smaller than 10^15, so only systems with unusual int/char sizes are a problem.

**Comment by benkrikler** [comment]
Just to explain my original concern, both http://www.cplusplus.com/reference/cstdio/snprintf/ and http://en.cppreference.com/w/cpp/io/c/fprintf mark `snprintf` as c++11.

**Comment by litchfld** [comment]
Indeed they do. I think it was formally added to C++ (in the std:: namespace) in C++11, but it has been in C99 and accessible to gcc's C++ compiler for a while.  (Similarly, C++ formally lacked a 64bit integer type until 2011, which is crazy.)
