### ISSUE TITLE
Minor changes to LoopSequence

### ISSUE THREAD

**Issue by benkrikler** [alcap-org/AlcapDAQ#175]
@litchfld, as well as those discussed on #170, are you happy for me to make the following changes:
- Catch std::exceptions and anything else in `Run`
- Add the following fields:  
  
  ```
  mutable long int fEntry;
  mutable BaseModule* fModule;
  ```
  
  which are set in the loops of the `process` methods and can be used for error reporting when an exception is thrown.  You're own exceptions have the event number already, but for std::exceptions this doesn't work.  Is there a reason why we don't just keep the entry number as a member of the LoopSequence class itself?

**Comment by litchfld** [comment]
I had been thinking along those lines, but decided against it...

Is there a reason to actually store these as ints/pointers?  If it is purely for messaging then it might be safer to create and store the reporting string as a string.  That avoids the risk of someone abusing the values for something else.

If that is the case, have a look at the newer exception classes I added since then.  They (are supposed to) let you add a reporting message when they are thrown.

**Comment by litchfld** [comment]
PS: I intended to purge these exceptions from feature/event_navigator at a later date anyway.  I started the exception classes in a separate feature, and I just wanted a place holder rather than trying to merge one branch into another.

**Comment by benkrikler** [comment]
I've changed the output so that we now see which module failed as well as the event number.  That answers the motivation for the above changes, though I implemented it by following your existing scheme of giving the values to the constructor and creating the message in the catch block.  It would be nicer if the message was produced in the exception itself, but this works for now so i'm going to leave it as is and let you sort it once you get back on to alcap.  Lucy you!

**Comment by benkrikler** [comment]
Oh, and I think we can close this for now then...

**Comment by litchfld** [comment]
_Lucy_?

**Comment by benkrikler** [comment]
Sorry, was I not meant to tell everyone?
