### ISSUE TITLE
PlotIntegral histograms have fewer entries than PlotAmplitude and PlotTime

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#182]
I'm still getting far fewer entries in the PlotIntegral plots than in the PlotAmplitude and PlotTime plots.

e.g. Ge-F
- 1.654818x10^7 (PlotTime)
- 1.654818x10^7 (PlotAmplitude)
- 2276591 (PlotIntegral)

There are also only 18 overflows in the PlotIntegral histogram.

I've had a quick look at the code and the PlotIntegral module is fine. It's looping through all the TAPs so why is this happening?

**Comment by benkrikler** [comment]
I noticed this as well, but I've not had time to solve it.  Is it possible
we over count in PlotAmplitudes?  They use the same approach (I believe
they were copy-and-paste jobs) so it's natural they'd agree between them.

**Comment by AndrewEdmonds11** [comment]
I'm worried that it's coming from hadding histograms with different axes. It just seems we have very few TDPs as well.

Do we see the same discrepancy in a single run? If not, what about hadding two runs? Can we remove the discrepancy by having set limits for the axes rather than auto scaling?

**Comment by dmalexan** [comment]
I noticed some questions in the elog about the odd structure in the integral plots.  These are likely due to amplitude overflows (definately so with the neutron detectors).  Unless we change the method to plot the integral from a fit, we can't do much to fix this. I had been cutting on overflows before, but this seems to contradict the current interests.

**Comment by benkrikler** [comment]
> I'm worried that it's coming from hadding histograms with different axes. It just seems we have very few TDPs as well.

Looking in the over / under flows would confirm this.

> Can we remove the discrepancy by having set limits for the axes rather than auto scaling?

Of course.  But I had no idea what limits were reasonable, so set it this way to get a sense.

**Comment by dmalexan** [comment]
setting the limit to something like 3 \* max bin should work (though it might be a bit low for Ge-S)

**Comment by litchfld** [comment]
> I'm worried that it's coming from hadding histograms with different axes. It just seems we have very few TDPs as well.

I was a bit surprised that hadd even worked with histograms of different sizes (it used to be a script that did TH1::Add, which aborts if the axes don't match). So I took a look, and yes it can do, but there are [caveats](http://root.cern.ch/root/html/TH1.html#TH1:Merge). In particular it will fail if the binning is different and:
- The output will have the same binning as the coarsest input, and all other inputs must be (i) finer by an _integer_ multiple; (ii) the limits must also be interger multiples of the larger bin with. Essentially it will never interpolate.
- If there are entries in the under/overflow bins.

I didn't look at [the controlling code](http://root.cern.ch/root/html/TFileMerger.html#TFileMerger:MergeRecursive) very closely but since TH1::Merge is an instance method hadd probably ends up outputting just the first histogram if the merge fails.  

It probably goes without saying that auto axis typically don't  line up except in rather particular cases. But the spectrum of a saturating ADC may be one of those cases.

**Comment by AndrewEdmonds11** [comment]
In the commit 2a681b234879fb8e71f87e2fea6128e84a7df88b, I have now set the axis limits in the PlotIntegrals function to be large enough to cover the Ge-S distribution. The others would need zooming in afterwards (I will add a function for this to the picture book program)
