### ISSUE TITLE
Further Optimisation of PulseCandidateFinder

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#184]
We need to further optimise the PulseCandidateFinder as explained issue #178

**Comment by AndrewEdmonds11** [comment]
From the amplitude plots we saw last week. We know that the slow silicon channels need their thresholds changing since we see small noise bump before the huge peak:

![sir1-2-s_amplitude_zoomin](https://cloud.githubusercontent.com/assets/1848575/3876630/df8876f8-215d-11e4-8f53-2cf37b49ade6.png)

I'm also inclined to think that the huge peak might also be due to poor pulses and so might move the threshold up a bit.

Also, I'm thinking that we should use the slow pulse finding algorithm (i.e. a simple amplitude threshold cut) for the fast pulses as well. Or at least the fast silicon channels since they are so noisy.

**Comment by AndrewEdmonds11** [comment]
For the slow silicon channels. I have compiled the following list from the PlotAmplitude histograms and recorded the value at which there is a gap between the small broad feature and the huge peak and the value when the number of pulses goes below 100.

| Channel | Amplitude at Gap [ADC] | Amplitude at N = 100 [ADC] | Previous Value [ADC] |
| --- | --- | --- | --- |
| SiL1-1-S | 45 | 55 | 20 |
| SiL1-2-S | 80 | 105 | 150 |
| SiL1-3-S | 100 | 135 | 20 |
| SiL1-4-S | 80 | 105 | 40 |
| SiL2-S | 30 | 80 | 20 |
| SiR1-1-S | 40 | 60 | 40 |
| SiR1-2-S | 60 | 75 | 60 |
| SiR1-3-S | 40 (NB no actual gap) | 75 | 40 |
| SiR1-4-S | 40 (NB no actual gap) | 70 | 40 |
| SiR2-S | 30 | 80 | 30 |

I'll look into the pulses to see how they look

**Comment by AndrewEdmonds11** [comment]
> I'll look into the pulses to see how they look

As we know, they don't look good. Also, I think it's going to be hard to find a good parameter (for slow pulses this is the sample height above pedestal) due to the very noisy pedestal.

To illustrate, both the following pulses have amplitudes of 106.74 ADC:
![notok_pulse_amp106](https://cloud.githubusercontent.com/assets/1848575/3889257/89f18cf8-220b-11e4-8853-2bf1254b6bb6.png)
![ok_pulse_amp106](https://cloud.githubusercontent.com/assets/1848575/3889258/8cd5e086-220b-11e4-8690-3791e25f276d.png)

where the first one is obviously awful and it's not so certain for the second one.

Here are few things I'll try:
- Move to using the `n_sigma` option which detects pulses that are a certain number of sigma above the pedestal
  - this should take into account the poor noise values that we have stored in the SQLite table for the silicon channels
- Implement a new algorithm with a running pedestal
  - this will have implications on where MaxBin gets the pedestal from (TAPs already have a field for pedestal so we will have to start filling this)

**Comment by litchfld** [comment]
Had a quick "high-level strategy" discussion with Andy.  Main thoughts:
- The _N sigma_ approach gives more lenient cuts, even at _10 sigma_.  Implication: the noise is not a pure Gaussian, which will make it harder to evaluate the efficiency and purity of the selection. This could be quite problematic later on, since a full hit level MC is a lot more work than planned. I doubt  we even have enough information to make one.
- I wondered if we are asking too much of the pulse finder to give us a clean set of pulses in one sweep. It might be better to regard the current algorithm as a pre-selection that identifies regions of interest, then use a more careful finder on the result to produce candidates (which are then fitted). In that approach:
  - The result of a ROI finder should include regions around the found feature as context for a more sophisticated finder to work with.
  - Neighbouring ROIs should be stitched together for a downstream algorithm to work on.
- We can still be hopeful this may 'come out in the wash' when we look at time-correlating things into events. Because of that perhaps the best approach right now is to assume that physics pulses are relatively rare, raise the finder cuts high, and push through to a completed analysis that may be inefficient.

To make the this into a more concrete suggestion: The rate of real physics pulses in any shouldn't be much higher than a fraction of the MuSc rates - and probably a lot lower given the solid angle acceptance.  So if we just start by tuning the threshold on each pulse to be about the same rates as good MuSc pulses, or a fraction of that (10%, or whatever looks plausible from 'clean' detectors) we should have a physics signal if there is one to be found.  We take that sample right through to a preliminary analysis (TMEs and some estimate of their quality) then look at how tweaking the pulse finder cuts affects the set of TMEs.

**Comment by AndrewEdmonds11** [comment]
This is pretty much finished in the above commit. It's worth noting explicitly that we now use the slow pulse finder algorithm (the simple amplitude cut) for the fast silicon channels.

I've set the silicon channels based on Phill's suggestion. First, I noted down where the gap between the small lump and the large peak in the amplitude plots is for each channel (for the fast channels I had to run about 60 runs). Then I tried to set threshold so that each channel in a set (all left slow, all left fast, all right slow, all right fast) had roughly the same number of TAPs being generated.

The conclusion is that we don't have many fast pulses compared to slow pulses (but we knew that already). Should I continue increasing the thresholds in the slow silicon channels so that the number of TAPs in the fast and slow are roughly the same?

| Channel | Gap | N_TAP @ Gap | Final Parameter Value | N_TAP @ Final Parameter Value | Note |
| --- | --- | --- | --- | --- | --- |
| muSc | N/A | N/A | 300 | 2 602 802 |  |
|  |  |  |  |  |  |
| SiL2-S | 30 | 19 254 | 100 | 5 053 | Used this as the baseline |
| SiL1-1-S | 45 | 28 325 | 50 | 4 006 |  |
| SiL1-2-S | 80 | 2 138 | 80 | 2 138 |  |
| SiL1-3-S | 100 | 15 686 | 120 | 6 444 |  |
| SiL1-4-S | 80 | 5 019 | 80 | 5 019 |  |
|  |  |  |  |  |  |
| SiL2-F | 80 | 4 096 | 300 | 234 |  |
| SiL1-1-F | 130 | 134 | 130 | 134 | Used this and the other segments as the baseline |
| SiL1-2-F | 500* | 13 | 500 | 13 | Even at threshold of 50 there are only 16 TAPs |
| SiL1-3-F | 135 | 90 | 135 | 90 |  |
| SiL1-4-F | 140 | 146 | 140 | 146 |  |
|  |  |  |  |  |  |
| SiR2-S | 30 | 16 855 | 100 | 5 391 | Used this as the baseline |
| SiR1-1-S | 40 | 52 687 | 55 | 3 717 |  |
| SiR1-2-S | 50 | 8 126 | 65 | 6 195 |  |
| SiR1-3-S | 55 | 50 262 | 65 | 6 807 |  |
| SiR1-4-S | 55 | 64 779 | 62 | 5 121 |  |
|  |  |  |  |  |  |
| SiR2-F | 80 | 4 286 | 300 | 229 |  |
| SiR1-1-F | 135 | 128 | 135 | 128 | Used this and the other segments as the baseline |
| SiR1-2-F | 140 | 147 | 140 | 147 |  |
| SiR1-3-F | 140 | 202 | 140 | 202 |  |
| SiR1-4-F | 130 | 2 536 | 150 | 113 |  |

*There isn't so much of a gap here but it's a reduction just before a big spike

**Comment by AndrewEdmonds11** [comment]
This has been merged into develop so I am closing this now and re-open should we need to do some more optimisation.
