### ISSUE TITLE
Recording time offset values by generator name+config

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#205]
There's the issue of recording TDiff values in the database. They should be recorded by the generator name, of course (template, cf, and max bin), but also by configuration options (constant_fraction=0.1, constant_fraction=0.2).

At the moment, my plan is to have a column name in a time offset table in the calibration database that is equal to the configuration string with a single option stripped. That is the option to ignore the time offsets or not. An example:

```
CFTime#{constant_fraction=0.1}{no_time_shift=yes}
CFTime#{constant_fraction=0.1}{no_time_shift=no}
CFTime#{constant_fraction=0.1}
CFTime#{no_time_shift=yes}{constant_fraction=0.1}
```

All refer to the same column in the table, which is `CFTime#{constant_fraction=0.1}`. I'd like to crowd source ideas on doing this differently.

**Comment by benkrikler** [comment]
An open call for different opinions on how to implement something and yet no one's replied within 4 hours!?  

So your proposal is to have a table for each generator whose schema is something like:

```
run INT | channel STRING | config_a_calib_value FLOAT | config_b_calib_value FLOAT | ..... 
```

?

Having a table for each generator sounds reasonable since the contents of the tables may be quite different for each generator.  And then using one column per configuration sounds good, provided it's easy to append a column or remove one for when we run again with a different configuration.

If appending a column is tricky, then maybe having a fresh table per configuration is better.  Then use some master table to index the table names to the various configurations.

That might be nicer if we re-use algorithms between generators as well.  The CFT algorithm only requires one set of constants but is reused in the FirstComplete and CFTime generators and could be reused again.  So having one master table that helps us identify which actual table to get the values from might make it easier to re-use and modify existing data.  It would be nice if the schema we develop now could be re-used immediately for the amplitude / integral calibration as well.  They will probably have at least 2 constants per run per channel, though the flexibility to have more would be good as well.

I'm thinking something like this then:
Master table:

```
channel STRING | CFT_10 INT | CFT_20 INT | ..... | max_bin INT | Integral INT
"MuSC"         | calib_1    | calib_2    | ....  | calib_9     | calib_10
"SiR2-S"       | calib_11   | calib_12   | ....  | calib_19    | calib_20
"SiL1-1-F"     | calib_21   | calib_22   | ....  | calib_28    | calib_29
```

Specific calib table (eg. calib_1)

```
run INT | const1 FLOAT | const2 FLOAT | ....
3739    | 0.340        | 189.4        | ....
3738    | 0.303        | 201.3        | ....
```

**Comment by jrquirk** [comment]
So originally I was going to have a single table called CoarseTimeOffset with columns run, channel, and then a variable number of columns named with the output of `TVAnalysedPulseGenerator::GetSource.Generator().str()`, except with the `{no_time_shift=yes/no}` parsed out, and I've stuck with that because the same problems arise no matter what. Problems we may have in the future are
- more configuration options for the generator, despite the timing method not changing, would mean the correct timing isn't grabbed because it returns a different generator string
- the order of the configuration options changing
- if a configuration option is introduced that has a default value that may or may not be present in the configuration string. This is strictly accommodated for only the no_time_shift option

Indexing by timing method would be better, and perhaps that should be done later. The timing calculations that were already finished can be reused of course, so things wouldn't need to be run again.  I'm closing this until it becomes an issue again.

**Comment by benkrikler** [comment]
I'm pretty sure we should be storing calibration per algorithm, not per generator although it's clearly a blurry line.  Certainly, in this case, all the above problems would be avoided if the columns were just labelled by the name of the algorthm and the CFT value.

I've been thinking as well that generator IDs rather than contain a flattened string version of the options, they should actually contain the option instance.  The string methods could all be made to work as they do currently, but then we could easily implement checks to see if a generator ran with a specific (non-default) option.  I'm going to put up a ticket to discuss this idea...

**Comment by jrquirk** [comment]
> I'm pretty sure we should be storing calibration per algorithm, not per generator...

We agree on this point. Generator was quicker to implement because I could just grab the string. This can change in the future without having to recalculate everything because we can just change column names by hand.

**Comment by litchfld** [comment]
Ugh.  Sorry, I haven't touched this in a while, so I'm maybe slightly off message. But i'm concerned that we are loosing our way here.  As far as my understanding goes:
- Different detectors have different definitions of `time=0` because they receive their timer reset signal   (which mayor may not be derived from the MIDAS event start, with a fixed unknown offset) at different times. This is primarily a cable delay but may also include the ordering of actions within the logic of the digitisers themselves
- These delays should be fixed, or only change under specific well described circumstances, because they are a feature of the readout system.
- Calibration tables, as stored in databases are intended to record these features of the readout, but generating these constants requires some analysis, of a calibration data set.
- Ideally the calibration should be independent of the analysis used to extract the constant.
- We should expect that  calibration _constants_ in the database are not dependent on analysis method.

Additional corrections may be necessary for particular algorithms. Ideally these additional corrections should be global (i.e. not require additional database tables) so they can just be applied by the algorithm as part of it's job. We might have to relax this partly or fully if we do not know enough to separate issues unambiguously, but this should be regarded as a special failure, not something we design in as routine.

I'm very concerned about Ben's suggestion of a master table.  This is rather quick-and-dirty approach to a much grander problem - one which is solvable but involves more subtleties than any of us really understand. We don't have the resources to pursue that sensibly.  If it's absolutely necessary we could take one from somewhere else, but to be honest I think we'd be better served by reducing our goals so this is not necessary - even if that slightly degrades our final analysis.
