### ISSUE TITLE
Pulse Candidates Finder and railed pulses

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#230]
Just to be certain, a pulse like

![railed_pulse](https://cloud.githubusercontent.com/assets/5143258/4170259/5b049132-3530-11e4-9dcd-8a6a03af9e59.png)

would show up as two pulses, one before the max and after?

**Comment by AndrewEdmonds11** [comment]
Umm.. I'm not sure.

This is one of the slow pulses so the PCF will start if the pulse height goes above a threshold. It will then stop when it goes below pedestal so, yes, I think it will be two pulses. Have you used the script I posted in #192?

**Comment by litchfld** [comment]
L:ooks like this would be easy to identify algorithmicly, but maybe we should just throw these out for now?

**Comment by jrquirk** [comment]
> ...maybe we should just throw these out for now?

I agree.

> Have you used the script I posted in #192?

Not yet. I'll try it out today. Thank you.

**Comment by benkrikler** [comment]
I've added the ability to overlay PCF candidates directly in ExportPulses.  Sorry for taking so long @AndrewEdmonds11.  Just stick `true` as the only argument to the ExportPulse constructor in the modules file:

```
[MODULES]
....
ExportPulse(true)
```

At the moment the PCF that's called will use the default start and stop pulse values since I didn't think anyone is doing anything else.  I can change this when it becomes important.  

Hopefully that helps John.

**Comment by jrquirk** [comment]
Cheers
