### ISSUE TITLE
Dead time in Ge

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#236]
Has anyone looked at the dead time due to transistor resets in the germanium? I want to try to not duplicate too much effort.

I would like to
- plot time of first hit after a reset in the germanium slow to get a feel see the dead time (in the fast the reset happens within a single TPI)
- count resets in calibration and regular data because the difference in dead time could affect the efficiency

**Comment by thnam** [comment]
I have some code on that. Will write something up here or on the wiki.

**Comment by thnam** [comment]
It seems to me that the dead time due to the reset pulses is not significant. The bigger dead time is from the long pulse length.

**Comment by thnam** [comment]
I plotted the time interval between two consecutive pulses on the Ge-S channel. This plot should give us an estimation of count rate, and in case of reset, a bump around 2 ms.
Plot from calibration runs 3375, 3378, 3379:
![ge_cal_rate_pulselength](https://cloud.githubusercontent.com/assets/4444606/4337313/40dd9c98-400e-11e4-899e-131cb8ed0838.png)

Some observations:
- average pulse length was about 45.7 us;
- time interval plot has exponential shape, the count rate was about ~ 240 cps. This count rate and the pulse length above give an estimation of correction for random summing: exp{2 x (rate) x(pulse length) = 1.02
- two bumps:
  - one at ~  2 ms, corresponds to reset pulses. Total number of resets was 2335, so the dead time due to this was ~ 4.6 s. This is small (0.14%) compare to total measurement period of 3245 s (number of blocks x block length). Its contribution is small compare to 2% from random summing above.
  - one at 200 us. I don't know what it is but suspect that it has something to do with triggering by other channel. The peak looks like Gaussian.

The interval plot from one of SiR2 runs:
![sir2_ges_self_tdiff](https://cloud.githubusercontent.com/assets/4444606/4337595/fbd854d2-4010-11e4-8957-e4ca9d564f65.png)
The counting rate was higher, 514 cps. The number of resets should increase linearly (?) with the count rate, so correction for them would be about 0.28%.

The random summing correction increases exponentially with the count rate. Also higher count rate makes the average pulse length longer, to 57 us in this case. Then the correction factor is 1.06 for this SiR2 run.

The plot above is from one SiR2 run (2119). I can imagine that making that plots for all runs could give us another mean to check the muon flux fluctuation.

Another note is that the bump at 200 us did not show up here. The wiring was different: in early SiR2 runs, only Ge-S was on UH CAEN; later we attached Ge-F on the WFD. This is why I suspect that bump would come from the common trigger.

**Comment by millerj2111** [comment]
Hi Nam,
Did you look at the spacing only within midas events, not 
between successive midas events?
--Jim

**Comment by millerj2111** [comment]
Hi Nam,
How do you get a Ge peak near the 2p-1s of Al from Pb212? 
What is teh mechansim?
Thanks.
--Jim

**Comment by jrquirk** [comment]
Thank you Nam.You've answered all of my questions.

**Comment by thnam** [comment]
Hi Jim,
- Yes, I calculated intervals within one Midas event only. The clock is resetting at the beginning of each block, so I don't think that we can reliably calculate things across multiple Midas events.
- The peak is background from the environment. And sorry, that was Pb-214 in the U-238 series. I took the number from the Practical Gamma-ray Spectroscopy (2nd. ed, Gordon Gilmore, p.363):
  ![screen shot 2014-09-20 at 8 01 43 am](https://cloud.githubusercontent.com/assets/4444606/4343281/04521f8e-4053-11e4-9e73-fb72711fe5f0.png)

The lines in bold are most prominent background peaks; the 1st column is energy in keV, 3rd column is intensity in %, the 4th column is the related peaks.
The 351 keV peak shows up all the time even in the runs without target.
