### ISSUE TITLE
Tagging code producing any numbers we quote

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#256]
Andy recently tried to reproduce some of my work and couldn't because I'd changed the code since I cited some number. Even I had to look back through the commit history to figure out why our numbers disagree.

I propose anytime we quote numbers (elogs, presentations, progress reports/beam requests) we tag the code, and I figured I'd open an issue to get confirmation of how good an idea this is.

**Comment by benkrikler** [comment]
Sounds like a good idea to me.  Do we want to agree the tag format? I think it should include the issue, elog or presentation in the name so we can look from tag to report as well as report to tag.  Maybe the tagger's name should be included as well?

**Comment by jrquirk** [comment]
Okay, I say <name>_<identifier>_<version>, with _elog###/issue###/conference/document_ being identifiers and names being last names. If people don't feel the need to version after that, like ignoring the __v#_, it won't make finding the tag any harder. And an omitted version number can implicitly be the first one.

The name might be redundant information since tags might include the tagging user, and additionally the annotation might hold info as well, but it can't hurt.

**Comment by AndrewEdmonds11** [comment]
I agree but is there a need to define a tag format? Can we not just put the relevant commit hash in every presentation we give? I can't think of an occasion where I'll be browsing through commit logs and wonder what conclusions people drew from them (although that could be a lack of imagination on my part).

Also, on a similar note. When we attach presentations to an elog we should write a small summary in the body of it so that it can be searched easily. I've had problems finding exactly which of my own presentations I wanted since I have uninformative presentation names and elog titles...

And, just thinking now, we can put these two together and get rid of the need for a specific tag format and can just copy the commit hash into the body of an elog so we can easily search for reports on the elog.

**Comment by jrquirk** [comment]
> Can we not just put the relevant commit hash in every presentation we give?

Why do tags exist if this is sufficient? Tags give us another method of searching through our work. Stale commits can get pruned under certain (admittedly unusual) circumstances. They're easier to remember while searching.

> When we attach presentations to an elog we should write a small summary in the body of it so that it can be searched easily.

I agree. Searching through anything titled "Agenda for..." is a hassle, so even in those throw up some keywords if there's an attachment instead of a separate elog.

**Comment by AndrewEdmonds11** [comment]
> Why do tags exist if this is sufficient?

Equally, we could ask why commits exist if tags are better :p. More seriously, I was just under the impression that tags should be used sparingly for specific releases that definitely work. 

My other gripe is that it's another thing to maintain and I just think that, in day-to-day life, I'm going to be writing a talk with numbers from some version of the code and then it's easier for me to just commit and get the hash, rather than commit, tag and make sure that my tag matches the convention.

But on the other hand, as I write this I wonder: can you easily checkout a commit from a different branch or is that only possible with tags (is it possible with tags?). If so, then I'd be more inclined to go with tags...

But on the other, other hand: how often would I be checking out someone else's code to do the cross-check rather than just looking through it to see where it differs? Probably, when things are really bad...

Anyway, we probably don't want to spend too long on these meta-discussions and I should probably go home.

Apologies for the stream of consciousness...

**Comment by benkrikler** [comment]
>  can you easily checkout a commit from a different branch
> 
> is it possible with tags?

Yes to both

> we could ask why commits exist if tags are better

Cause Tags are human readable (and memorable) whereas you need a unique commit ID and no-one wants to have to think of something original every time they commit.  Moreover, the commit's hash is made based on a function of the entire contents of the commit so it's very easy to check that two commits are the same or not.

> My other gripe is that it's another thing to maintain

What's the additional maintenance?  Just make a tag and push it when you want to mention results somewhere.  We dont have to look after, tidy up or update the tags at any point...

**Comment by AndrewEdmonds11** [comment]
> What's the additional maintenance?

Maybe maintenance is the wrong word but it's an extra thing to do, right? Without using tags I can just give you the commit hash and that's it. I can even give details about elogs and things in the commit message if needs be. 

I just don't see what we gain by using tags for this...

**Comment by jrquirk** [comment]
We've concluded these both work. If we run into problems down the line, we can revisit this.
