### ISSUE TITLE
TMEs containing multiple copies of the same TDP

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#266]
So I've just noticed a bug where I'm getting the same bin in my dE/dx plot filled multiple times (I don't know why I didn't see this sooner).

Putting in some cout statements to tell me the TME number, the sources, the number of pulses in each source and which pulse I am currently plotting, I see that there are two thin pulses in the same quadrant with the same energy:

```
TME #20
Arm: SiL
Thick source: SiL2#PassThrough#any, n_pulses = 1
Thick Pulse #0
Thin source: SiL1-1#PassThrough#any, n_pulses = 2
Thin Pulse #0
Amplitude --> Energy (thick): 174.77 --> 1387.83
Amplitude --> Energy (thin): 55.19 --> 181.036
Plotting: 1568.87, 181.036

TME #20
Arm: SiL
Thick source: SiL2#PassThrough#any, n_pulses = 1
Thick Pulse #0
Thin source: SiL1-1#PassThrough#any, n_pulses = 2
Thin Pulse #1
Amplitude --> Energy (thick): 174.77 --> 1387.83
Amplitude --> Energy (thin): 55.19 --> 181.036
Plotting: 1568.87, 181.036
```

Obviously, this could be the reason why my proton rate is so much higher than Nam's so was looking for some help (_cough_ @benkrikler _cough_) to get to the bottom of it.

At the moment, I'm looking into the FixedWindowMEGenerator and I'm wondering what happens if there is only one pulse in the source? The start iterator presumably points to that pulse but then does the stop iterator point to the end? (Obviously it works, we can see that in the output above that the thick pulse only has one pulse)

The only other place I can think to look is the PassThrough generator. I know that a while ago, I had a problem where, because I'm only using the slow pulses and the PassThrough generator always put any pulse in the "fast" TAP slot, that I had to do this in my TME_Al50_EvdE module:

``` C++
const TDetectorPulse* tdp_si_thin=(*i_tme)->GetPulse(si_thin_source,i_thin_pulse);
double thin_energy = tdp_si_thin->GetTAP(TDetectorPulse::kFast)->GetEnergy();
```

Could it be something to do with this?

**Comment by rhbob** [comment]
I’ve made trivial mistakes enough to be suspicious somebody is counting like a C array and has a <= sign instead of a <

Are we in C++11?  Then use (or if not C++11, just define the iterator)

for (auto it = s.begin(); it != s.end(); it++){
std::cout << *it << std::endl;
}

—bob

Robert Bernstein

DPF Executive Committee
Fermi National Accelerator Laboratory
office: (630) 840-2035
cell:    (708) 846-1782
rhbob@fnal.govmailto:rhbob@fnal.gov

On Feb 25, 2015, at 5:32 AM, Feb 25, 2015, AndrewEdmonds11 <notifications@github.com<mailto:notifications@github.com>> wrote:

So I've just noticed a bug where I'm getting the same bin in my dE/dx plot filled multiple times (I don't know why I didn't see this sooner).

Putting in some cout statements to tell me the TME number, the sources, the number of pulses in each source and which pulse I am currently plotting, I see that there are two thin pulses in the same quadrant with the same energy:

TME #20
Arm: SiL
Thick source: SiL2#PassThrough#any, n_pulses = 1
Thick Pulse #0
Thin source: SiL1-1#PassThrough#any, n_pulses = 2
Thin Pulse #0
Amplitude --> Energy (thick): 174.77 --> 1387.83
Amplitude --> Energy (thin): 55.19 --> 181.036
Plotting: 1568.87, 181.036

TME #20
Arm: SiL
Thick source: SiL2#PassThrough#any, n_pulses = 1
Thick Pulse #0
Thin source: SiL1-1#PassThrough#any, n_pulses = 2
Thin Pulse #1
Amplitude --> Energy (thick): 174.77 --> 1387.83
Amplitude --> Energy (thin): 55.19 --> 181.036
Plotting: 1568.87, 181.036

Obviously, this could be the reason why my proton rate is so much higher than Nam's so was looking for some help (cough @benkriklerhttps://github.com/benkrikler cough) to get to the bottom of it.

At the moment, I'm looking into the FixedWindowMEGenerator and I'm wondering what happens if there is only one pulse in the source? The start iterator presumably points to that pulse but then does the stop iterator point to the end? (Obviously it works, we can see that in the output above that the thick pulse only has one pulse)

The only other place I can think to look is the PassThrough generator. I know that a while ago, I had a problem where, because I'm only using the slow pulses and the PassThrough generator always put any pulse in the "fast" TAP slot, that I had to do this in my TME_Al50_EvdE module:

const TDetectorPulse\* tdp_si_thin=(*i_tme)->GetPulse(si_thin_source,i_thin_pulse);
double thin_energy = tdp_si_thin->GetTAP(TDetectorPulse::kFast)->GetEnergy();

Could it be something to do with this?

**Comment by AndrewEdmonds11** [comment]
Problem solved!

It was because the PulseCandidateFinder wasn't disabled properly (apparently `use_pcf=false` doesn't go in the `MakeAnalysedPulses` options but in the`FirstCompleteAPGenerator` options). 

Everything looks OK now (I don't see any repeated TDPs) so once Merlin is back up, I will rerun my analysis again and see if I get a number that is closer to Nam's _fingers crossed_.

**Comment by thnam** [comment]
I am looking forward to this!

**Comment by benkrikler** [comment]
> It was because the PulseCandidateFinder wasn't disabled properly (apparently use_pcf=false doesn't go in the MakeAnalysedPulses options but in theFirstCompleteAPGenerator options). 

It's been a while, but I think that was done since using the PulseCandidateFinder is a decision left up the generator, rather than the MakeAnalysedPulse module itself.

I hope this works now.  I'm not sure I understand why the PCF would have this impact though...

**Comment by AndrewEdmonds11** [comment]
Actually, I think it was because I'd set the parameter values to 0 on the PCF so that I could effectively switch it off but still use the PCF to remove overflowed pulses. When I was debugging, I noticed that I was getting a few sub pulses on each TPI but I'm not sure why they were returning the same TPI trigger time, TPI length, energy etc.

Anyway, I'll ignore the overflowed pulses for now since they had a small effect on the final result and post here any result.

**Comment by AndrewEdmonds11** [comment]
Finally managed to do a new production of Al50 and quickly ran it through my analysis chain (graphical proton cut, unfolding etc.) and I now get (between 4 and 8 MeV) a proton emission rate of 0.016. I haven't done the errors yet but this is now consistent with Nam's 1.7%!! :smile::smile::smile:

I'm currently doing some work on systematics for my thesis, so hopefully this will all coalesce and be written up thoroughly in a couple of weeks.
