### ISSUE TITLE
Odd Island Timestamp Plot (Ge-S (CaUH), Runs 2091 - 2096, SiR dataset)

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#45]
Hi John

I'm currently recompiling and testing the picture book scripts and have noticed that for runs 2091 - 2096 (SiR dataset), the Ge-S timestamps plot doesn't go up to ~110ms. Did you see this before?

Cheers
Andy

**Comment by jrquirk** [comment]
It was there in the first production run as well.

**Comment by jrquirk** [comment]
The ODB says that for the batch of runs 2091-2096 is 1e8 Hz, whereas later it's 1.6129e7 Hz. This is a factor difference of 6.2, which is also the factor separating 110ms and where the timestamps actually end (~18 ms).

I believe the ODB is probably wrong, and in the process of making the plot the timestamps were scaled down incorrectly because of this. But I'm copying a file over now to look at the raw timestamps.

**Edit**
Confirmed: https://muon.npl.washington.edu/elog/mu2e/RunPSI2013/379

This needs an ODB fix. I'll hardcode some special fixes into the ODBChecker.

**Comment by jrquirk** [comment]
The newest version of the ODBChecker changes all UH CAEN channels for runs 2091-2103 to have a frequency of 1.6129e+07. It's hardcoded in a method in the WireMap class UniqueFixes(). So, you know, not elegant.
