### ISSUE TITLE
Make not recognising header file changes

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#48]
I'm not sure if this is particular to my feature branch, but I don't see why it would be.  

If I make an edit to a .h file this does not trigger the necessary recompilations of all dependent files.  A simple test:

``` bash
$ make
[output completes OK]
$ touch src/framework/FillHistBase.h
$ make
[make does not update anything]
```

Can someone check if this happens for them?

I looked quickly at the makefile and auxiliaries, but didn't dig deep. Although we have $(CXX) -MM lines in the Makefile, and we get the generated dependency files in obj/ , they don't seem to be being used.

**Comment by benkrikler** [comment]
You're exactly right.  I've seen this for a while but never got around to resolving it.  There's no explicit dependencies on the header files and the `$(CC) -MM` files are not being picked up because the targets they contain don't have the right form for the current Makefile, which would be '$(OBJ_DIR)/%.o'.  Is there a way to set this sort of prefix for the object name that $(CC) -MM generates?  I rewrote a lot of the makefile to make it's output more intuitive and to store the object and dependency files elsewhere than the top-level, but I broke this aspect in the process I guess...

**Comment by benkrikler** [comment]
Ok, so I stopped being lazy and read the man page a bit:

```
 -MT target
           Change the target of the rule emitted by dependency generation.  By default CPP takes the name of the main input file, deletes
           any directory components and any file suffix such as .c, and appends the platform's usual object suffix.  The result is the
           target.

           An -MT option will set the target to be exactly the string you specify.  If you want multiple targets, you can specify them as a
           single argument to -MT, or use multiple -MT options.

           For example, -MT '$(objpfx)foo.o' might give

                   $(objpfx)foo.o: foo.c
```

I think that should do it....

**Comment by benkrikler** [comment]
This should now be solved on develop...

**Comment by AndrewEdmonds11** [comment]
Just a note that in git flow, hotfixes are also merged into master so are only for really urgent things that affect our releases. 

Ben, it looks like you just named this branch "hotfix/..." and it didn't get merged into master. For quick fixes like this that aren't really features but are also not really hotfixes, should we have another name? Or am I just being overly pedantic and it's fine the way it is?

**Comment by benkrikler** [comment]
Yeah, I realised that when I tried to merge it all in.  I thought it was just a feature with a different name...  The reason it's not in master is because i haven't pushed master since I finished the hotfix.  

I don't think the name is the problem so much, just a problem with the way we use git flow / it was envisaged.  You make feature branches off develop, and don't seem able to make small fixes.  Can we just agree that for simple bug fixes that only affect one file, we can work on develop directly?

**Comment by AndrewEdmonds11** [comment]
I could agree to that, it's simple and I think it would also look good on the network graph. I have a small reservation of there being clashes if someone finishes a feature branch while you're doing a fix but I don't think that's a major consideration

**Comment by litchfld** [comment]
Works for me, tnx

> I could agree to that, it's simple and I think it would also look good on the network graph.

o_O

**Comment by litchfld** [comment]
> I don't think the name is the problem so much, just a problem with the way we use git flow / it was envisaged. You make feature branches off develop, and don't seem able to make small fixes. Can we just agree that for simple bug fixes that only affect one file, we can work on develop directly? 

Actually I think that is envisaged as part of the standard git flow work flow: http://nvie.com/img/2009/12/Screen-shot-2009-12-24-at-11.32.03.png
