### ISSUE TITLE
Possible Extension of ExportPulse Module

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#52]
I just want to ask @benkrikler some questions about something he said on issue #7 but thought it would be best to keep it separate

> Something I've been considering doing which be useful here is to extend the TAP base class to have a DrawResult() method which you can overload so the ExportPulses module could use it to overlay the TAP results on the TPI...

This sounds like a good idea in principle but I'm trying to see exactly how it would be used in the template generator. What would we be plotting on top of the TPI? Or would we just be writing, say, the chi^2 to the file at the same time?

**Comment by benkrikler** [comment]
So the basic idea was something like:
1. ExportPulses module is asked to draw a pulse 
2. ExportPulses draws that TPI's waveform
3. ExportPulses looks up the TAP
   - I'm not sure of the implementation of this part, i've opened issue #53 to discuss it.
4. For each TAP it obtains in step 3. call TAP::DrawResult(TCanvas*):
   - This method is virtual in TAnalysedPulse
   - By default it would probably just put a marker to show the recovered time and amplitude
   - If you specialise a TAP by deriving from it (Eg. TTemplateFitAnalysedPulse) you can overload this method to do something fancy.  In TTemplateFitAnalysedPulse, for example, I would have it draw the fitted template (ie. scaled and shifted by the recovered amplitude and time) on top of the TPIs waveform.
   - If you thought it was helpful you could add a label to the plot with the fit results of that pulse but it's up to you.

Steps 1 and 2 are done and accessible within the code (similar to your original version) or through the config file specifying an event and a pulse number.  The work that's needed is in steps 3 and 4.  4 is easy but 3 I'm unsure about at this point..

**Comment by benkrikler** [comment]
So based on discussion on #53 ,  my thinking has changed on this a bit.  I'll replace the AddExportToPulseList(detector,pulseID) with AddExportToPulseList(source, TAP*).  This makes more sense for accessing this module within code because it's only from a TAP that we know that the pulse is worth drawing.  This would also then allow the TAP -> TPI look-up directly which solves my question for step 3 above.

**Comment by benkrikler** [comment]
From the above commit, f228cfe, I have implemented the extension suggested in this thread.  TAPs now have a Draw method which currently takes a pointer to a const version of the histogram of the TPI corresponding to that TAP.  The default method is to draw a histogram with the bin corresponding to the measured time filled with the measured amplitude and all other bins zero.  This is a virtual method so that people creating specialised TAPs (such as for the template fit or the neutron detector) can draw other representations.

The histogram produced for the TPIs and the TAPs are stored in the root file, so you need to open the file and call `Draw()` and `Draw("same")` respectively to see the overlaid result.

I think this is safe to close now, but feel free to re-open or add more comments if necessary.
