### ISSUE TITLE
Cannot find libRootanaDataClasses.so

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#55]
I've just rebased teature/template_tap_generator and, after a few more changes to get rootana to compile, I try to run rootana and I get the following error:

```
./rootana: error while loading shared libraries: libRootanaDataClasses.so: cannot open shared object file: No such file or directory
```

I tried, re-making in the alcapana data_quality directory and then make clean and make but it didn't solve the problem. Any help?

**Comment by AndrewEdmonds11** [comment]
And that library is in the analyzer/rootana directory...

**Comment by AndrewEdmonds11** [comment]
Solved by running this command in the terminal:

```
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
```

But I'm not sure if this is the idea....

**Comment by thnam** [comment]
Tried to compile it and found this dependency:

```
LIB_DATACLASS := $(DAQdir)/analyzer/work/$(USER)/libDataClasses.so
```

Does it mean that we still need to compile alcapana before rootana?

**Comment by benkrikler** [comment]
@AndrewEdmonds11 :

> Solved by running this command in the terminal:
> 
> > export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH

I'm assuming you're current working directory was AlcapDAQ/analyzer/rootana.  This is done for you in thisdaq.sh.  My guess is you didn't go from fresh or re-source the script and so this change wasn't picked up. It's been in since I touched the makefile.

@thnam: 

> Does it mean that we still need to compile alcapana before rootana? 

Yes.  I've not changed that yet ( #27 ). Though it is something we would like to do in the future, as we're all compiling alcapana anyway I don't think it's a priority at this time.

Can I close this then?

**Comment by AndrewEdmonds11** [comment]
Ok, I really freshen up my screen sessions from time to time then.

Closed.
