### ISSUE TITLE
GitFlow Updating Feature Branches with Any Updates to Develop

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#6]
What's the git flow command we're supposed to use to get any updates to the develop branch into our feature branches?

**Comment by benkrikler** [comment]
It's got to be one of `git flow feature pull` or `git flow feature rebase` no?

The git flow "help" gives:

```
       git flow feature rebase [-i] [<name|nameprefix>]
       git flow feature pull [-r] <remote> [<name>]
```

Looking in the files that define these commands (in /usr/share/gitflow/git-flow-feature for me), the rebase -i option makes it interactive and pull -r will use rebase to apply changes instead of merging them.  

I think the rebase option is the one you want, though I'm not 100% on it..

**Comment by AndrewEdmonds11** [comment]
Yes, doing a bit of searching it seems that rebase is recommended (see http://stackoverflow.com/questions/16440433/merge-a-branch-with-git-flow-keeping-the-branch-still-alive).

I've just tried doing this on `feature/template_tap_generator` with the command:

```
git flow feature rebase
```

and it seemed to work. (Note that it didn't seem to like being given the name of the develop branch). 

I had to resolve one conflict between develop and feature during the rebase. Then, when I tried pushing to github, I had to pull first and resolve another conflict (basically the same one again) before being able to push. 

Everything seems to look OK on the network graph so I think it worked :)

**Comment by litchfld** [comment]
Crap. Remind me, what command do I use to do a merge if there is a conflict?  

And which of the three-way-diffed files needs to be brought up to date?

**Comment by AndrewEdmonds11** [comment]
I was going to write a reply but it's easier if I come downstairs

**Comment by benkrikler** [comment]
But post it to the wiki or this issue once you solve things so we all
benefit.

**Comment by AndrewEdmonds11** [comment]
So if you get a conflict when merging what you have to do is
- open the file in a text editor
- there will be lines like <<<<<, ===== and >>>>>, which indicate where the conflict is and which code is with which version
- manually change the file until it is how it should be
- `git add [file]`

Then you can recommit or continue the rebase or whatever you were doing.

**Comment by thnam** [comment]
There is a nice tool called kdiff3 for 3-ways merging. Just put this in your .gitconfig
[merge]
  tool = kdiff3

**Comment by litchfld** [comment]
That's what threw me,  git flow doesn't send you into the normal git three-way merge (I usually use meld rather than kdiff).  

TBH though, until I find an explanation of what git expects you to do with its three file variants I kinda prefer the old CVS-style (<<<<<< ====== >>>>>>) merges. So much for "git make merging a pleasure"!
