### ISSUE TITLE
Is there a way to get the run number from within a module?

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#75]
Title says it all really.

I want to use the run number as the title in plots and I'm wondering if there's a way to get this. Is it a global variable somewhere?

**Comment by benkrikler** [comment]
The short answer is no it's not currently available at some global scope, or wrapped up somewhere.  In principle, we have this in `arguments.run`.  This value contains either the value given through the command line, or if this is not given, taken from the filename of the input file.

Does this count as run-time configuration?  If so I'll add a method to the modules::navigator to get this information.  I think the event navigator might be better suited, but it's a while longer until its useable I think.

**Comment by benkrikler** [comment]
Now you can do:

``` c++
SetupNavigator::Instance()->GetRunNumber();
```

It uses either the run number given on the command line or else obtains it from the input file name.  Ideally we would cross check this against a value contained in the file probably in TSetupData I'd guess?

I wasn't exactly sure where to put this method and I'm not certain it's the best place.  This SetupNavigator class only handles the run number at the moment, but it should, in time, completely absorb TSetupData, so that all future access to that class goes through this.
