### ISSUE TITLE
Do we need a default  generator config?

### ISSUE THREAD

**Issue by litchfld** [alcap-org/AlcapDAQ#80]
I'm going through and making my interfaces fit Ben's new classes. One thing i'm not sure of, if a generator has no configuration what does it use for it's config string? The default argument is `" "`, but it would be nice from a documentation point of view to make that a string constant, like `kAnyConfig` is. Say `kDefaultConfig` or `kDefault`.  Also it would be better if that default string were something other than `" "`, since that is a little tricky to spot a trailing space on tty. `"_"` is better, but perhaps `"default"` is better still.

**Comment by benkrikler** [comment]
Just to clarify, when you say no configuration, you mean no configuration specified by the modules file, not that the module cannot be configured by the file?

That sounds like a good suggestion though.  I think `kDefaultConfig` is the best name for the variable but since I can imagine someone using 'default' as a real option in the MODULES file, I'd say we use some other value.  How about just "NoOptions"?

This might also mean changing the implementation of [`IDs::generator::str()`](http://alcap-org.github.io/doxygen/AlcapDAQ/develop/classIDs_1_1generator.html#a180be08adbdc2729c4a65ba50171dc19), so it shows the config part for all values.

**Comment by litchfld** [comment]
> Just to clarify, when you say no configuration, you mean no configuration specified by the modules file, not that the module cannot be configured by the file?

Either I think.  It could be a module that does not make sense to configure and therefore has no options, or  a module that can be configured but is running in it's default mode.  But if anyone writes a module where `"default"` can be specified as an option and is not the default behaviour, they should be considered a danger to society.

> This might also mean changing the implementation of IDs::generator::str(), so it shows the config part for all values.

Not sure. I guess it's a little easier for me to parse the string if there always guaranteed to be something in that position (`AnyConfig => "*"`, `Default(Config) => "default"` maybe) but it is sort of seems nice that the AnyConfig can be omitted. And `"*"` in particular might get difficult as part of a branch name (...which reminds me, I need to open an issue on that.)

**Comment by benkrikler** [comment]
This has been done as described in the above commit. Closing....
