### ISSUE TITLE
Move to Using MuCap/MuLan Job Daemon Script

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/AlcapDAQ#91]
As I guess you all saw, Peter Winter suggested that we look into using the MuCap and MuLan job submission script daemon (https://muon.npl.washington.edu/cgi-bin/cvsweb/jobscripts/ncsa_abe/ or attached to his e-mail) which could be very useful.

**Comment by benkrikler** [comment]
Was this email to the whole list?  I didn't get it....

Also, that link needs a password and the standard ones don't seem to work.

**Comment by AndrewEdmonds11** [comment]
Oh, I thought it was but having just checked it's only to me. Here's the text and I'll foward the e-mail to everyone since there's an attachment on it. 

I didn't manage to get to that link either but put it there in case someone could:

```
Dear AlCap analyzers,

sorry I missed a couple of analysis calls but the CD2/3 review for g-2 is taking 120% of my time. However, I once mentioned that we had an SQlite based job daemon script for the processing of the large number of MIDAS files in MuCap and MuLan. I know this would be quite some effort to first understand how this worked and then adapt it to AlCap at Merlin but in the long term it might pay off. Managing the several stages of analysis and output files becomes quite tedious. I have attached an elog from MuCap describing the steps how to setup the scripts (although it might be a bit outdated). And at this link here <https://muon.npl.washington.edu/cgi-bin/cvsweb/jobscripts/ncsa_abe/> are all the scripts that we had for the processing in MuCap. If anybody was interested into setting something up like this, I am happy to help. In addition, Volodya was also heavily involved in getting this going in the first place.
Thanks
Peter
> Hello Everyone
>
> Everything is now ready to begin our third (and, hopefully, final) production run with alcapana, where our main aims are:
>  - to make sure our ODB corrections line everything up nicely
>  - get our tree files for use in rootana
>
> I have finished updating the instructions on elog:123 (https://muon.npl.washington.edu/elog/mu2e/Analysis-R13/123), where I have also assigned people to do some datasets.
>
> If you have any problems with running your jobs, then open an issue on GitHub and I (or someone else) can try to answer.
>
> Thanks
> Andy
> _______________________________________________
> AlCapCollaboration mailing list
> AlCapCollaboration@u.washington.edu
> http://mailman13.u.washington.edu/mailman/listinfo/alcapcollaboration


-- 
Peter Winter
Assistant Physicist
Argonne National Laboratory
High Energy Physics
Bldg 362, Room E-269
9700 S Cass Avenue
Argonne, IL 60439

Tel: +1 630 252 6150 
```

**Comment by jrquirk** [comment]
Duncan Prindle sent me his stuff a while back. There was apparently some miscommunication. It's not a job daemon quite like it was suggested. It's just a script that submits things and tracks them through their multi-stage process. I don't know quite how rootana is going to work out as far as dealing with multiple stages, but I guess we could use it for alcapana->rootana stuff. Anyway, here's the email he sent. I'll load the code to the AlcapDAQ repo in a bit.

>  Hi John,
> 
>  Of course you can do anything you want with those scripts. I haven't gotten around to dealing with staging data yet.
> What the scripts do well are to start with a list of runs (as an SQLite table) and keep track of the status as they are processed through various stages. A possible drawback is I decided to use bash scripting for some reason. With google it's pretty easy to figure out how to do something in any language but I could understand if you wanted to re-write  in a more familiar language. The sql commands at the heart of it are pretty cool though.
> 
>  On re-reading your mail I'm confused. The scripts used on Lonestar aren't daemonesque, they simply submit appropriate groups of batch jobs. I did modify a perl script which we use in a fast offline analysis. It runs on one of the local computers during data taking, analyses a file and when finished asks for the next one based on a mysql database. Sort of like a daemon.
> 
>  In any case if you have access to the code then have at it. If you have any questions don't hesitate to ask. It might be nice to coordinate efforts. As I mentioned I didn't deal with staging yet. Also there should be a way to update the database when data is moved around.
> 
> ```
>  Duncan
> ```
> 
> > On 04/30/2014 03:05 PM, John Quirk wrote:
> > Hi Duncan,
> > 
> > My name is John Quirk, a BU graduate student working on the AlCap experiment with Peter Kammel et. al. We are entering analysis production soon and currently have an ad-hoc job submission system for the Merlin cluster at PSI.
> > 
> > I've heard rave reviews about a job daemon you wrote for MuSun from a number of people here at BU, and Peter Winter has suggested we switch to something more concrete. A number of things MuSun does to process runs AlCap needs as well. We need to stage the data, clone the ODB, run on lists of good runs, and use a batch system (Sun Grid Engine) with commands similar to what you use on Lonestar.
> > 
> > Would it be okay if we ported over your job daemon for our use, or use it as a guide for our own job daemon?
> > 
> > Cheers,
> > --John Q.

**Comment by jrquirk** [comment]
I finally uploaded the MuSun job scripts rewritten from Volodya/Brendan/whoever's scripts by Duncan Prindle [here](https://github.com/alcap-org/musun_job_scripts). I'll take a look at it this weekend, and other people can, too, now.

Also, Merlin has sqlite3 installed on it. Though I haven't tested it beyond just running the interactive prompt.

**Comment by jrquirk** [comment]
I spent a few hours on Friday and Saturday thinking about this, and probably the most difficult part is coming up with a good schema for the database. There are a number of ideas I got from the MuSun stuff and around the internet. I've done nominal work on it so far, posted at feature/jobscripts.

## General Goal

It'd be nice to be able to run a single command and have the program be able to figure out how to get the data, process it, and clean up. Without necessitating assignments and searching our email for the FTP password. We have some of this, to some degree, already.

## Database Location

I was thinking of putting it in my data/ directory, and giving read/write access to everyone. For backup purposes, we can do text dumps which are version-control friendly to the repo (when we tag a version of the code).

## Utilities

We'd need to check the amount of space and clean up old files if we need more. We'd need to be able to tell how many jobs are running from a user without the MacGyver'd lock files solution.

## DB Schema

This weekend I learned a SQL database is a collection of tables, and a table is composed of rows and columns. So the one table I'm confident we'll need is

### Run table
- Run number
- Dataset
- Data quality

And then some others

### Production List
- Production number
- Production type (alcapana/rootana)
- Start time
- Stop time
- Version base

For "version base" I was thinking for alcapana it would be which alcapana production run odb check was run on (so for production run 3, it would be production run 2) and for rootana it would be which version of alcapana it's based on (again, which production run). The noun "production" is ill-defined.

### Production Status
- Run number
- Run processing status
- User
- Submission time
- Start time
- Finished time
- File Location

The name of the table would be productiontype_versionnumber. I say file location because, when we need to make space, we might just have to delete files so this could be set to null if it was deleted, or moved to some sub-directory if the file exists and another production is run.

## FTP Password

I'm thinking people save the password in a text file on Merlin with permissions 600, maybe even in a directory with similar access so people don't know it's there, and then we just read from the file. Certainly not version controlled.

## Status

I've written some functions to parse the outputs of `mmlsquota`, `qstat`, and `qsub`, and to download the remote file via python instead of bash.

Discuss.

**Comment by litchfld** [comment]
I've not processed all this yet. But to get the ball rolling: there should be a software tag in the production list table. =)

**Comment by jrquirk** [comment]
> I'm thinking people save the password in a text file on Merlin

In response to what Phil suggested, this is no longer the plan. Now the password is expected to be in the user's [~/.netrc](http://www.mavetju.org/unix/netrc.php) file (with permissions 600) as this is a (very) standard, easy way to go about FTP connections. And python has standard libraries for dealing with ftp connections using netrc files.
